CREATE TABLE IF NOT EXISTS asset_categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       VARCHAR(64)  NOT NULL,
  name       VARCHAR(255) NOT NULL,
  parent_id  BIGINT,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT asset_categories_code_uq UNIQUE (code),
  CONSTRAINT asset_categories_name_uq UNIQUE (name),
  CONSTRAINT asset_categories_parent_fk
    FOREIGN KEY (parent_id) REFERENCES asset_categories (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS assets (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 VARCHAR(255) NOT NULL,
  model                VARCHAR(255),
  spec                 VARCHAR(255),
  category_id          BIGINT,
  supplier             VARCHAR(255),
  serial_number        VARCHAR(128),
  location             VARCHAR(255),
  owner_department     VARCHAR(255),
  status               VARCHAR(32) NOT NULL DEFAULT 'IN_STOCK',
  purchase_date        DATE,
  warranty_expire_date DATE,
  purpose              VARCHAR(255),
  unit_value           NUMERIC(14, 2),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT assets_category_fk
    FOREIGN KEY (category_id) REFERENCES asset_categories (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS asset_codes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id     BIGINT NOT NULL,
  code_type    VARCHAR(64) NOT NULL,
  code_value   VARCHAR(128) NOT NULL,
  is_primary   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT asset_codes_unique_uq UNIQUE (code_type, code_value),
  CONSTRAINT asset_codes_asset_fk
    FOREIGN KEY (asset_id) REFERENCES assets (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS access_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_code_id BIGINT NOT NULL,
  snapshot_path VARCHAR(1024),
  actor_type    VARCHAR(32),
  actor_id      VARCHAR(64),
  actor_name    VARCHAR(255),
  source_system VARCHAR(64),
  event_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  device_id     VARCHAR(255),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT access_logs_asset_code_fk
    FOREIGN KEY (asset_code_id) REFERENCES asset_codes (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS presence_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type  VARCHAR(32),
  subject_id    VARCHAR(64),
  subject_name  VARCHAR(255),
  source_system VARCHAR(64),
  device_id     VARCHAR(255),
  zone          VARCHAR(255),
  snapshot_path VARCHAR(1024),
  confidence    NUMERIC(5, 2),
  event_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_assets_category_status
  ON assets (category_id, status);

CREATE INDEX IF NOT EXISTS idx_asset_codes_asset_id
  ON asset_codes (asset_id);

CREATE INDEX IF NOT EXISTS idx_asset_codes_type_value
  ON asset_codes (code_type, code_value);

CREATE INDEX IF NOT EXISTS idx_asset_codes_code_value
  ON asset_codes (code_value);

CREATE INDEX IF NOT EXISTS idx_access_logs_code_time
  ON access_logs (asset_code_id, event_time);

CREATE INDEX IF NOT EXISTS idx_access_logs_event_time
  ON access_logs (event_time);

CREATE INDEX IF NOT EXISTS idx_asset_categories_parent_id
  ON asset_categories (parent_id);

CREATE INDEX IF NOT EXISTS idx_presence_logs_subject_time
  ON presence_logs (subject_id, event_time);

CREATE INDEX IF NOT EXISTS idx_presence_logs_device_time
  ON presence_logs (device_id, event_time);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_assets_updated_at'
  ) THEN
    CREATE TRIGGER trg_assets_updated_at
    BEFORE UPDATE ON assets
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_asset_categories_updated_at'
  ) THEN
    CREATE TRIGGER trg_asset_categories_updated_at
    BEFORE UPDATE ON asset_categories
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_asset_codes_updated_at'
  ) THEN
    CREATE TRIGGER trg_asset_codes_updated_at
    BEFORE UPDATE ON asset_codes
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

